package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildSteps.NodeJSBuildStep
import jetbrains.buildServer.configs.kotlin.buildSteps.nodeJS
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build")) {
    expectSteps {
        nodeJS {
            id = "nodejs_runner"
            shellScript = "npm run build"
        }
    }
    steps {
        update<NodeJSBuildStep>(0) {
            name = "install"
            clearConditions()
            shellScript = "npm run install"
            param("teamcity.kubernetes.executor.pull.policy", "")
        }
        insert(1) {
            nodeJS {
                name = "test"
                id = "test"
                shellScript = "npm run test"
            }
        }
        insert(2) {
            nodeJS {
                name = "build"
                id = "build"
                shellScript = "npm build"
            }
        }
    }
}
